version: "3.8"
services:
  sonarqube:
    ports:
      - "7000:9000"
      - "7002:9002"
    image: sonarqube
  dotnetscanner:
    depends_on: [sonarqube]
    environment:
    - PROJECT_KEY=key
    - PROJECT_NAME=project_name
    - PROJECT_VERSION=1.0.0
    - SONAR_HOST_URL=http://localhost:7000
    command: >
      bash -c "cd source && dotnet /sonar-scanner/SonarScanner.MSBuild.dll begin 
      /k:$${PROJECT_KEY} 
      /name:$${PROJECT_NAME} 
      /version:$${PROJECT_VERSION}
      /d:sonar.host.url="$${SONAR_HOST_URL}" 
      && dotnet build -c Release  
      && dotnet /sonar-scanner/SonarScanner.MSBuild.dll end"
    image: nosinovacao/dotnet-sonar:latest
    volumes:
      - "/:/source"
    network_mode: host